# Generated by Django 5.1 on 2024-09-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='marketCapValue',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='volumeQty',
            field=models.IntegerField(null=True),
        ),
    ]
