# Generated by Django 5.1 on 2024-09-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_stock_marketcapvalue_stock_volumeqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='remainingVol',
            field=models.IntegerField(null=True),
        ),
    ]
