# Generated by Django 5.1 on 2024-09-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0003_stock_remainingvol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='marketCapValue',
        ),
    ]
