# Generated by Django 5.1 on 2024-09-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0004_remove_stock_marketcapvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Buy', 'Buy'), ('Sell', 'Sell')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
