# Generated by Django 5.1 on 2024-09-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0005_contactmessage_transaction_transactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pricePurchased',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
