# Generated by Django 5.1 on 2024-09-25 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0006_transaction_pricepurchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='priceTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
